language: php

php:
- 7.1
- 7.2
- 7.3

before_install:
- composer install

#before_script:
#- phpenv config-rm xdebug.ini

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
