language: php

php:
- 7.0
- 7.1
- 7.2
- 7.3

matrix:
  fast_finish: true
  allow_failures:
  - php: 7.3

before_install:
- composer install --dev

before_script:
- phpenv config-rm xdebug.ini

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
